{% set name = "Flask-Admin" %}
{% set version = "1.5.0" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "88618750e08ceee1ab232a5a9ebcef31275db5db1c0b56db29e014c24c7067a4" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  number: {{ build_num }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - flask >=0.7
    - wtforms
    # Required for flask_admin.contrib.appengine:
    # - wtforms-appengine
    # Required for flask_admin.contrib.geoa:
    # - geoalchemy2
    # - shapely
    # Required for flask_admin.contrib.mongoengine:
    # - flask-mongoengine
    # Required for flask_admin.contrib.peewee and flask_admin.contrib.peeweemodel:
    # - peewee
    # - wtf-peewee
    #  Required for flask_admin.contrib.pymongo:
    # - pymongo
    # Required for flask_admin.contrib.sqla and flask_admin.contrib.sqlamodel:
    # - sqlalchemy

test:
  imports:
    - flask_admin
    - flask_admin.contrib
    - flask_admin.contrib.fileadmin
    - flask_admin.form
    - flask_admin.model
    - flask_admin.translations

about:
  home: https://github.com/flask-admin/flask-admin/
  license_file: LICENSE
  license: BSD 3-Clause
  license_family: BSD
  summary: 'Simple and extensible admin interface framework for Flask'
  doc_url: https://flask-admin.readthedocs.io/en/latest/
  dev_url: https://github.com/flask-admin/flask-admin/

extra:
  recipe-maintainers:
    - pmlandwehr
