{% set name = "Flask-Admin" %}
{% set version = "1.5.4" %}
{% set compress_type = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_val = "ed7b256471dba0f3af74f1a315733c3b36244592f2002c3bbdc65fd7c2aa807a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip

  run:
    - python
    - flask >=0.7
    - wtforms
    # Required for flask_admin.contrib.appengine:
    # - wtforms-appengine
    # Required for flask_admin.contrib.geoa:
    # - geoalchemy2
    # - shapely
    # Required for flask_admin.contrib.mongoengine:
    # - flask-mongoengine
    # Required for flask_admin.contrib.peewee and flask_admin.contrib.peeweemodel:
    # - peewee
    # - wtf-peewee
    #  Required for flask_admin.contrib.pymongo:
    # - pymongo
    # Required for flask_admin.contrib.sqla and flask_admin.contrib.sqlamodel:
    # - sqlalchemy

test:
  imports:
    - flask_admin
    - flask_admin.contrib
    - flask_admin.contrib.fileadmin
    - flask_admin.form
    - flask_admin.model
    - flask_admin.translations

about:
  home: https://github.com/flask-admin/flask-admin/
  license: BSD 3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: 'Simple and extensible admin interface framework for Flask'
  doc_url: https://flask-admin.readthedocs.io/en/latest/
  dev_url: https://github.com/flask-admin/flask-admin/

extra:
  recipe-maintainers:
    - pmlandwehr
    - xylar
