{% set name = "Flask-Admin" %}
{% set version = "2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') | lower }}-{{ version }}.tar.gz
  sha256: 1d06aec7efee957972b43f6b08a0bd08d5f4cf9a337d4ece2f17c98abc2a214e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - flit-core <4
  run:
    - python >={{ python_min }}
    - flask >=2.0
    - jinja2 >=3.0
    - markupsafe >=2.0
    - werkzeug >=2.0
    - wtforms >=2.3
    # for all python to stay noarch:python
    - typing_extensions

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - flask_admin
    - flask_admin.contrib
    - flask_admin.contrib.fileadmin
    - flask_admin.form
    - flask_admin.model
    - flask_admin.translations
  commands:
    - pip check

about:
  home: https://github.com/flask-admin/flask-admin/
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Simple and extensible admin interface framework for Flask
  doc_url: https://flask-admin.readthedocs.io/en/latest/
  dev_url: https://github.com/flask-admin/flask-admin/

extra:
  recipe-maintainers:
    - pmlandwehr
    - xylar
