{% set name = "Flask-Admin" %}
{% set version = "1.6.1" %}
{% set compress_type = "tar.gz" %}
{% set hash_val = "24cae2af832b6a611a01d7dc35f42d266c1d6c75a426b869d8cb241b78233369" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  sha256: {{ hash_val }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.6
    - pip

  run:
    - python >=3.6
    - flask >=0.7
    - wtforms

test:
  requires:
    - pip
  imports:
    - flask_admin
    - flask_admin.contrib
    - flask_admin.contrib.fileadmin
    - flask_admin.form
    - flask_admin.model
    - flask_admin.translations
  commands:
    - pip check

about:
  home: https://github.com/flask-admin/flask-admin/
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Simple and extensible admin interface framework for Flask
  doc_url: https://flask-admin.readthedocs.io/en/latest/
  dev_url: https://github.com/flask-admin/flask-admin/

extra:
  recipe-maintainers:
    - pmlandwehr
    - xylar
