{% set name = "Flask-Admin" %}
{% set version = "2.0.0" %}
{% set compress_type = "tar.gz" %}
{% set hash_val = "c5878ab1ea92c9e8345c0e1a2cd15851f5ecf2e1616d7fb9158487769f188e81" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') | lower }}-{{ version }}.tar.gz
  sha256: {{ hash_val }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - flit_core <4
  run:
    - python >={{ python_min }}
    - flask >=2.0
    - jinja2 >=3.0
    - markupsafe >=2.0
    - werkzeug >=2.0
    - wtforms >=2.3
    # for all python to stay noarch:python
    - typing_extensions

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - flask_admin
    - flask_admin.contrib
    - flask_admin.contrib.fileadmin
    - flask_admin.form
    - flask_admin.model
    - flask_admin.translations
  commands:
    - pip check

about:
  home: https://github.com/flask-admin/flask-admin/
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Simple and extensible admin interface framework for Flask
  doc_url: https://flask-admin.readthedocs.io/en/latest/
  dev_url: https://github.com/flask-admin/flask-admin/

extra:
  recipe-maintainers:
    - pmlandwehr
    - xylar
