travis:
  secure:
    BINSTAR_TOKEN: r/rfANgG2jrnSz5vGZnLA8GDrAjc6s9S3oFdKW8b0XLwfpNGvCi/xJnAGPddS0ymx4imDQP3I+IjgYpEnV6ctxI3ZP/hbYsZyFfjVcMTxhYN4uNkDcmZVzyxwQoD0QrMvdEOXyUIqpOX5XLfbFp/wOtmapCjvyeOqAS3RRIYuoFfoDHupE5QUZhzJwOWRLxSwfZGCf2wLJW/NtaAbKCphplKox9REMMdmsIOfIWeVXFAo8X1WrVI34s+jkciZbit6spaWyDUt6KwJE1Yau4QNRt2eQgSsKG0Oim3SYV6z9MbPCxZEKf7Ym++8N2a5ubHkKcvK0ISfyAveoD0V0osLEjXl/yZ74+7MIT8op7IhibG6uQKYBK0yUJY2tODfm/AeMe4SCKmQuRHrxDPcO37nOvt6VVUDN/aj09Y00Jd5OCSGYRrh9eFaz1XjW/uzXt3apalXxR1gLXCZWvSDZIPR3cNoIsVwpdQSd6NHoqCEZm1o+rDVGaS444+ic76v7zV5sr4v0esW8fchVQIk4bG162t+auQFYdvo84BG4LvNqCgqhacw1aLBY5WmDQHdWFwY62xO8DYnIp7i2ER6FZJ2K59NNTVYUCloF9vlMcSE0A3RZwK7pD6KqmVJ3/p8ikLtD749rpAefIC8f+pQHmFUgJIcjHjouIe3h45wvUs060=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
